name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    pull_request:
        branches: [main]
        types: [opened, reopened]
    push:
        branches:
            - "**/**"
jobs:
    dependabot:
        runs-on: ubuntu-latest
        if: ${{ github.actor == 'dependabot[bot]' }}
        steps:
            - name: Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v1
              with:
                  github-token: "${{ secrets.GH_TOKEN }}"
