name: "DP"
on: [pull_request]

permissions:
    contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
        with:
         fail-on-severity: low
         allow-licenses: GPL-3.0, BSD-3-Clause, MIT, ISC
         deny-licenses: LGPL-2.0, BSD-2-Clause
         allow-ghsas: GHSA-abcd-1234-5679, GHSA-efgh-1234-5679
         fail-on-scopes: development, runtime
