name: "Dependency Review"
on: [pull_request]

permissions:
    contents: read
    pull-requests: write

jobs:
    dependency-review:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v3
            - name: "Dependency Review"
              uses: actions/dependency-review-action@v3
              with:
                  fail-on-severity: low
                  vulnerability-check: true
                  comment-summary-in-pr: true
                  license-check: true
                  allow-licenses: GPL-3.0, BSD-3-Clause, MIT
                  allow-ghsas: npm
                  repo-token: "${{ secrets.GH_TOKEN }}"
                  config-file: './.github/workflows/actions.yml'
                  base-ref: ${{ github.event.pull_request.base.sha || 'master' }}
                  head-ref: ${{ github.event.pull_request.head.sha || github.ref }}
