name: "DP"
on: [pull_request]

permissions:
    contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.base_ref }} ${{ github.head_ref }}"
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
        with:
          deny-licenses: ISC
