name: 'Dependency Review'
on: [pull_request]

permissions:
  discussions: write
  contents: read
  pull-requests: write
  

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Run audit'
        id: audit
        uses: oke-py/npm-audit-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
      - name: Print Status Success
        if: steps.audit.outcome  == 'success'
        run: echo SUCCESS!
      - name: Print Status failure
        if: steps.audit.outcome  == 'failure'
        run: echo failure!=(((
