name: 'Dependency Review'
on: [pull_request]

permissions:
  discussions: write
  contents: read
  pull-requests: write
  

jobs:
  dependency-review:
    runs-on: macos-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: Install zsh-syntax-highlighting
        run: |
          brew update
          brew install zsh-syntax-highlighting
          brew install node
      - name: Run a zsh script as proof
        run: |
          node -v
      - name: 'Run audit'
        id: audit
        uses: oke-py/npm-audit-action@v2
        continue-on-error: true
        with:
          audit_level: high
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability
      - name: Print Status Success
        if: steps.audit.outcome  == 'success'
        run: echo '${{ toJSON(steps.audit) }}'
      - name: Print Status failure
        if: steps.audit.outcome  == 'failure'
        run: echo '${{ toJSON(steps.audit) }}'
