name: 'Dependency Review'
on:
  pull_request:
     paths-ignore:
       - 'src/*.ts'

permissions:
  discussions: write
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Print github
        run: |
            echo '${{ toJSON(github) }}'
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
      - name: Npm install
        run: |
          npm install
      - name: Run Audit
        id: audit
        uses: oke-py/npm-audit-action@v2
        with:
         audit_level: critical
         github_token: ${{ secrets.GITHUB_TOKEN }}
         issue_assignees: oke-py
         issue_labels: vulnerability
      - name: Status success
        if: steps.audit.outcome  == 'success'
        uses: hmarr/auto-approve-action@v3
      - name: Status failure
        if: steps.audit.outcome  == 'failure'
        run: echo '${{ toJSON(steps.audit) }}'

