name: 'Dependency Review'
on: [pull_request]

permissions:
  discussions: write
  contents: read
  pull-requests: write
  

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh;sudo apt install zsh-syntax-highlighting;sudo apt install nodejs
      - name: Zsh-huh
        run: |
          node -v
          npm audit
      - name: 'Run audit'
        id: audit
        uses: oke-py/npm-audit-action@v2
        continue-on-error: true
        with:
          run: .github/bin/zsh_proof.sh
          shell: /usr/bin/zsh{0}
          audit_level: high
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability
      - name: Print Status Success
        if: steps.audit.outcome  == 'success'
        run: echo '${{ toJSON(steps.audit) }}'
      - name: Print Status failure
        if: steps.audit.outcome  == 'failure'
        run: echo '${{ toJSON(steps.audit) }}'
