name: 'Dependency Review'
on: [pull_request]

permissions:
  discussions: write
  contents: read
  pull-requests: write
  

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Run audit'
        uses: oke-py/npm-audit-action@v2
        with:
          audit_level: high
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability
          dedupe_issues: true
      - name: Print Status
        if: (${{ success() }}
        run: echo SUCCESS!
